"""initial schema

Revision ID: b633c3c15bf2
Revises: 
Create Date: 2026-08-06 20:01:12.584791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b633c3c15bf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', name='ai_topic_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mini_project', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.create_table('career_wins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('win_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_wins_win_date'), 'career_wins', ['win_date'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('researching', 'target', 'applied', 'interviewing', 'offer', 'rejected', name='company_status'), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea', sa.String(length=500), nullable=False),
    sa.Column('stage', sa.Enum('idea', 'writing', 'scheduled', 'posted', name='content_stage'), nullable=False),
    sa.Column('content_type', sa.Enum('tweet', 'linkedin', 'blog', 'readme', name='content_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('repurposed_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repurposed_from_id'], ['content_ideas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('win', sa.String(length=1000), nullable=True),
    sa.Column('learning', sa.String(length=1000), nullable=True),
    sa.Column('blocked_by', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_entries_entry_date'), 'daily_entries', ['entry_date'], unique=True)
    op.create_table('dsa_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('understanding', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('needs_revision', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern')
    )
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_companies', sa.JSON(), nullable=False),
    sa.Column('salary_goal', sa.String(length=120), nullable=True),
    sa.Column('deadline', sa.String(length=120), nullable=True),
    sa.Column('north_star', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('what_built', sa.Text(), nullable=True),
    sa.Column('what_learned', sa.Text(), nullable=True),
    sa.Column('what_slowed', sa.Text(), nullable=True),
    sa.Column('what_stop', sa.Text(), nullable=True),
    sa.Column('what_proud', sa.Text(), nullable=True),
    sa.Column('what_next', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_reviews_month_start'), 'monthly_reviews', ['month_start'], unique=True)
    op.create_table('notes_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('idea', 'in_progress', 'paused', 'done', name='project_status'), nullable=False),
    sa.Column('current_sprint', sa.Text(), nullable=True),
    sa.Column('next_milestone', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('to_read', 'reading', 'done', name='reading_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_design_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('diagram', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Boolean(), nullable=False),
    sa.Column('implemented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.create_table('weekly_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('git_commits', sa.Integer(), nullable=False),
    sa.Column('project_features', sa.Integer(), nullable=False),
    sa.Column('dsa_patterns_revised', sa.Integer(), nullable=False),
    sa.Column('system_design_topics', sa.Integer(), nullable=False),
    sa.Column('twitter_posts', sa.Integer(), nullable=False),
    sa.Column('linkedin_posts', sa.Integer(), nullable=False),
    sa.Column('blog_updates', sa.Integer(), nullable=False),
    sa.Column('books_articles', sa.Integer(), nullable=False),
    sa.Column('mock_interviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_metrics_week_start'), 'weekly_metrics', ['week_start'], unique=True)
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('what_built', sa.Text(), nullable=True),
    sa.Column('what_learned', sa.Text(), nullable=True),
    sa.Column('what_slowed', sa.Text(), nullable=True),
    sa.Column('what_stop', sa.Text(), nullable=True),
    sa.Column('what_proud', sa.Text(), nullable=True),
    sa.Column('what_next', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reviews_week_start'), 'weekly_reviews', ['week_start'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'screening', 'interviewing', 'offer', 'rejected', 'withdrawn', name='application_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_company_id'), 'applications', ['company_id'], unique=False)
    op.create_table('project_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('column', sa.Enum('ideas', 'todo', 'in_progress', 'done', name='kanban_column'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_cards_project_id'), 'project_cards', ['project_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=120), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_project_cards_project_id'), table_name='project_cards')
    op.drop_table('project_cards')
    op.drop_index(op.f('ix_applications_company_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_weekly_reviews_week_start'), table_name='weekly_reviews')
    op.drop_table('weekly_reviews')
    op.drop_index(op.f('ix_weekly_metrics_week_start'), table_name='weekly_metrics')
    op.drop_table('weekly_metrics')
    op.drop_table('system_design_topics')
    op.drop_table('resume_versions')
    op.drop_table('reading_list')
    op.drop_table('projects')
    op.drop_table('notes_pages')
    op.drop_index(op.f('ix_monthly_reviews_month_start'), table_name='monthly_reviews')
    op.drop_table('monthly_reviews')
    op.drop_table('mission')
    op.drop_table('dsa_patterns')
    op.drop_index(op.f('ix_daily_entries_entry_date'), table_name='daily_entries')
    op.drop_table('daily_entries')
    op.drop_table('content_ideas')
    op.drop_table('companies')
    op.drop_index(op.f('ix_career_wins_win_date'), table_name='career_wins')
    op.drop_table('career_wins')
    op.drop_table('ai_topics')
    # ### end Alembic commands ###
